### ISSUE TITLE
Как исправить, чтобы тест выводил 3?

### ISSUE THREAD

**Issue by denis-trofimov** [andrewyagodkin/Python_Courses#1]
https://github.com/andrewyagodkin/Python_Courses/blob/c415911e487ad53901a3553442d8f517510a2809/strings_compare.py#L24-L30

```
Введите строки для сравнения ниже, или "exit" для выхода из программы
Ввод строки: learn1  
Ввод строки: learn
2
```

**Comment by andrewyagodkin** [comment]
Поменял местами условия-сейчас работает корректно
